name: 'Split PHP tests by timing'
description: 'A custom PHP action to split PHP tests by timing'
inputs:
  junit-xml-report-dir:
    description: 'The directory path where the last test junit reports exist.'
    required: true
  node-total:
    description: 'The total number of the expected parallel nodes.'
    required: true
  node-index:
    description: 'The index of the current node.'
    required: false
    default: null
  xml-partial-dir:
    description: 'The directory path where the partial phpunit xml files will be placed.'
    required: true
  test-directories:
    description: 'List of comma separated test directories to use all test files inside it.'
    required: false
    default: 'tests/Feature,tests/Unit'
  debug:
    description: 'Debug option to echo some data that enables following up the flow.'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: version number
      run: echo "version: 1.0.2"
      shell: bash
    - env:
        INPUT_XML_PARTIAL_DIR: ${{ inputs.xml-partial-dir }}
        INPUT_NODE_INDEX: ${{ inputs.node-index }}
        INPUT_NODE_TOTAL: ${{ inputs.node-total }}
        INPUT_JUNIT_XML_REPORT_DIR: ${{ inputs.junit-xml-report-dir }}
        INPUT_TEST_DIRECTORIES: ${{ inputs.test-directories }}
        INPUT_DEBUG: ${{ inputs.debug }}
        BASE_PATH: ${{ github.workspace }}
      run: php ${{ github.action_path }}/phpunit-xml-splitter.php
      shell: bash
