name: 'Split PHP tests by timing'
description: 'A custom PHP action to split PHP tests by timing'
inputs:
  junit-xml-report-dir:
    description: 'The directory path where the last test junit reports exist.'
    required: true
  node-total:
    description: 'The total number of the expected parallel nodes.'
    required: true
  node-index:
    description: 'The index of the current node.'
    required: false
    default: null
  xml-partial-dir:
    description: 'The directory path where the partial phpunit xml files will be placed.'
    required: true
  debug:
    description: 'Debug option to echo some data that enables following up the flow.'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - run: ls -alh
      shell: bash
    - run: php /phpunit-xml-splitter.php
      shell: bash
